apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - amg_grafana-identity.yaml
  - amg_grafana-amp-datasource.yaml
  - amg_grafana-cw-datasource.yaml
  - amg_grafana-xray-datasource.yaml
  - amg_grafana-dashboards-amp.yaml
	- amg_grafana-dashboards-eks-infra.yaml
	- amg_grafana-dashboards-java.yaml
	- amg_grafana-dashboards-nginx.yaml
